version: '3.4'

services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    environment: 
      MYSQL_ROOT_PASSWORD: 123s
      MYSQL_DATABASE: Products
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123s
    volumes: 
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    command: ['--default-authentication-plugin=mysql_native_password']

  my-api:
    image: myapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"

volumes: 
  dbdata:
